usgs/earthquake-website

gruntconfig/config.js, gruntconfig/connect.js, gruntconfig/watch.js, package.json, src/htdocs/index.scss
This change is explicitly pulling in the new template and setting the ports to the new standards.
No content is changed.
=> Usgs/hazdev template#188

src/htdocs/data/comcat/catalog/ci/index.php
remove redundant information (that is output based on template and JSON info).
fix broken link to contributor page.
=> Update CI catalog page

src/htdocs/data/comcat/catalog/rdemineral/index.php
Updated the RDE mineral page based on google doc
=> Update rde mineral

src/htdocs/data/comcat/contributor/nc/index.json, src/htdocs/data/comcat/contributor/nc/index.php
Jennifer Taggart at Berkeley Seismological Lab here. My supervisor Peggy Hellweg just had me make a couple of updates to the NC network page. I followed the instructions I was sent by email, please let me know if there are any problems.
=> Updated web page for NC Network

src/htdocs/data/comcat/catalog/ci/index.php
updated status of ci ComCat load on ci catalog page.
=> updated catalog page to show updated status of load into Comcat

src/htdocs/data/comcat/catalog/ld/index.json, src/htdocs/data/comcat/contributor/ld/index.json, src/htdocs/data/comcat/contributor/pal/index.json
revised contact information to Mitch Gold @ LDEO
=> LD patch 1

src/htdocs/data/comcat/contributor/brk/index.json
Updated address, email, phone number, and website for BRK network contributor page.
=> Updated address, email, phone number, and website for BRK contributor

src/htdocs/data/_navigation.inc.php, src/htdocs/data/comcat/catalog/atlas/index.json, src/htdocs/data/comcat/catalog/us/index.json, src/htdocs/data/comcat/data-availability.php
=> updated ComCat data availability

src/htdocs/index.css, src/htdocs/index.php
=> added title and hid it with CSS so browser bar will have website title

src/htdocs/monitoring/operations/stations/README.md
Adding for comment, Lisa please wait to merge.
Fixes usgs/earthquake-network-operations#6
=> Initial documentation for Station JSON

src/htdocs/monitoring/operations/_navigation.inc.php, src/htdocs/monitoring/operations/_station.php
- Fixes navigation
- Fixes error in _station.php
=> Station fix

src/htdocs/monitoring/operations/_station.php, src/htdocs/monitoring/operations/network.php
Network attribution for the station views was added.
Removed the datalogger entry for the network display and fixed a typo in the column headings.
I did not have the ability to test my php function on a development system.
=> a few minor changes to the station tables

src/lib/sql/mysql/nc_workshop.md, src/lib/sql/mysql/nc_workshop.sql
=> separate sql dump and describe the table

src/htdocs/learn/kids/become.php, src/htdocs/learn/topics/eqmonitoring/buildings.php, src/htdocs/learn/topics/eqmonitoring/comparison.php, src/htdocs/learn/topics/eqmonitoring/history.php, src/htdocs/learn/topics/eqmonitoring/today.php
Applied comments on the pages from pull request "Learn work #559"
=> Applied comments to learn pages

src/htdocs/contactus/menlo/workshop/index.php
oops, sorry. I forgot to switch to https.
=> switch form submission to https addr

src/htdocs/scenarios/catalog/_catalog.inc.php, src/htdocs/scenarios/catalog/catalog.css, src/htdocs/scenarios/catalog/catalog.js
@lisa-usgs This is a general mock for the link to the map. I've included an image to show what it should look like with the placeholder text/image.
=> Update scenario catalog pages to provide a link to the map/list

src/htdocs/data/comcat/_functions.inc.php, src/htdocs/scenarios/_functions.inc.php
- Needs to be staged for testing
=> allows cooperator logos to work useing https

src/htdocs/learn/glossary/index.php
Let me know if there's still strangeness.
=> Fixed glossary database error

src/htdocs/learn/publications/pubs_factsheets.php, src/htdocs/learn/publications/pubs_geninfo.php, src/htdocs/learn/publications/pubs_maps.php, src/htdocs/learn/publications/pubs_multimedia.php, src/htdocs/learn/publications/pubs_ofr_bull_circ.php
let me know if there is still strangeness.
=> publications error fix

src/htdocs/learn/glossary/index.php
There was still some weirdness on the dev pages on some of the letters. It was an easy fix so I just went ahead and fixed. Hopefully the page is now done.
=> small glossary page weirdness fixed

src/htdocs/learn/publications/pubs_factsheets.php, src/htdocs/learn/publications/pubs_geninfo.php, src/htdocs/learn/publications/pubs_maps.php, src/htdocs/learn/publications/pubs_multimedia.php, src/htdocs/learn/publications/pubs_ofr_bull_circ.php
There was some issue I believe with having multiple blocks of php code, so I combined it all into one block.
=> Fix publications syntax errors

src/htdocs/_config.inc.php
=> changed default contact to lisa@usgs.gov

src/htdocs/learn/topics/listen/allsounds.php, src/htdocs/learn/topics/listen/combination.php, src/htdocs/learn/topics/listen/distance.php, src/htdocs/learn/topics/listen/rocktype.php, src/htdocs/learn/topics/listen/source.php, src/htdocs/learn/topics/listen/wavtest.php
Still working on the popup modal windows
=> Added audio/mp4 tags

gruntconfig/config.js, src/htdocs/monitoring/operations/_station.php, src/htdocs/monitoring/operations/conf/config.inc.php, src/htdocs/monitoring/operations/network.php
This fixes https compatibility for the monitoring/operations pages.
=> Netops https updates

src/htdocs/learn/topics/shakingsimulations/background.php, src/htdocs/learn/topics/shakingsimulations/people.php, src/htdocs/learn/topics/shakingsimulations/seealso.php
in background.php people.php and seealso.php. This was breaking the nav bar and site template on these pages.
=> removed inclusions of old css file

src/htdocs/earthquakes/events/1906calif/virtualtour/_navigation.inc.php, src/htdocs/earthquakes/events/1906calif/virtualtour/instructions.php
=> fixed back link on navigation

src/htdocs/earthquakes/events/1868calif/virtualtour/_navigation.inc.php, src/htdocs/earthquakes/events/1868calif/virtualtour/global.php
=> fixed issues

src/htdocs/earthquakes/browse/stats.js, src/htdocs/earthquakes/browse/stats.php
It loads pretty slowly at first. But loading after that first one is pretty fast. I tried a different way that loads faster at first, but then more slowly later on.
=> Making stats dynamic

src/htdocs/earthquakes/events/1868calif/index.php, src/htdocs/earthquakes/events/1989lomaprieta/index.php
=> Small fixes to fix broken links and blockquotes

src/htdocs/earthquakes/events/1868calif/index.php, src/htdocs/earthquakes/events/1906calif/index.php, src/htdocs/earthquakes/events/1989lomaprieta/index.php, src/htdocs/earthquakes/events/_navigation.inc.php
=> Fixing Titles

src/htdocs/hazards/hazmaps/conterminous/index.php
=> added errata and qa link

src/htdocs/data/comcat/contributor/nc/index.json, src/htdocs/data/comcat/contributor/nc/index.php
Added reference to NCSS, Mission, ShakeMaps link, Contributing Networks, changed Regional Partners for NC contributor page, as discussed by email on 4/23.
=> latest edits to NC contributor landing page

src/htdocs/data/comcat/contributor/nc/index.php
I had typos in two of my URLs for the NC contributor page. These are fixed now with this pull request, sorry about that!
=> Fixed two typos on NC contributor page.

src/htdocs/data/comcat/catalog/_catalog.inc.php, src/htdocs/data/comcat/contributor/_contributor.inc.php
Changed text "Mailing Address" to "Address" in contributor and catalog templates, as requested by Peggy Hellweg.
=> Changed text "Mailing Address" to "Address" in contributor and catalog templates

src/htdocs/hazards/designmaps/usdesigndoc.php
@nluco-usgs : Do these changes seem okay to you?
=> USDesign Doc Updates

src/htdocs/learn/glossary/functions.glossary.inc.php, src/htdocs/learn/kids/kidsLearningLinks.php, src/htdocs/learn/preparelinks.php, src/htdocs/learn/publications/pubs_factsheets.php, src/htdocs/learn/publications/pubs_geninfo.php, src/htdocs/learn/publications/pubs_maps.php, src/htdocs/learn/publications/pubs_ofr_bull_circ.php, src/htdocs/learn/today/_imbed.inc.php, src/htdocs/learn/today/index.php, src/htdocs/learn/topics/display.inc.php, src/htdocs/learn/topics/index.php, src/htdocs/learn/topics/topics.php
Make errors show in logs, but not on production pages.
=> INC000010147763

package.json, src/htdocs/highlight-archives.css, src/htdocs/highlight-archives.php, src/htdocs/index.css, src/htdocs/index.php, src/htdocs/research/everyone/2015/_features.inc.php, src/htdocs/research/everyone/2015/index.php, src/htdocs/research/everyone/2016/_features.inc.php, src/htdocs/research/everyone/2016/index.php, src/htdocs/research/everyone/2017/_features.inc.php, src/htdocs/research/everyone/2017/index.php, src/htdocs/research/everyone/_navigation.inc.php, src/htdocs/research/everyone/index.php, src/htdocs/research/everyone/styles.css, src/htdocs/research/index.php, src/lib/Features.class.php
and also added Highlights Archive page and link from Home
=> modifications to Research for Everyone to accomodate more each year

src/htdocs/data/comcat/contributor/av/index.json
@lisa-usgs please deploy this. Just a typo fix, thanks.
=> fix avo contributor.json

src/htdocs/monitoring/operations/heliplot.php, src/htdocs/monitoring/operations/network.php
@lisa-usgs : please deploy these fixes.
=> Escape virtual network before including in title

src/htdocs/data/comcat/contributor/ok/index.json, src/htdocs/data/comcat/contributor/ok/index.php
=> OGS additions

src/htdocs/research/parkfield/discontinued.php, src/htdocs/research/parkfield/instrument_table.php, src/htdocs/research/parkfield/seismic.php
=> udpate links

src/htdocs/index.php
As discussed on call with Glenn and Valerie
=> Add link to ShakeAlert from homepage
